### PR TITLE
DC-0 instrument model

### PR DESCRIPTION
**Pull request by zonca**
Imported DC-0 instrument model using the notebook included in this pull request.
Also double-checked that the CHLAT properties did not change.

@smsimon could you please double-check the parameters? should we keep using top-hat bandpasses?

### CODE REVIEW

**Comment by zonca** [comment]
@jdborrill @keskitalo the naming of the CHLAT channels changed from `LFL1` to `CHLAT_f030`. So the maps of the past CHLAT run are named  `LFL1`, while the future runs will be named `SPLAT_f020` for example. My suggestion is to re-run the map-domain simulations with the new naming scheme to have it all consistent, and then compare the maps of the new run to the maps of the old run to make sure that nothing changed significantly. What do you think?

**Review by smsimon — APPROVED** [review]
Looks consistent to me

**Comment by keskitalo** [comment]
Comparing to the earlier simulations sounds like a good plan.

**Comment by jdborrill** [comment]
Sounds good. You might also point Elena to the outputs for independent
verification/sanity checks.

The one issue is that Reijo has been running against the old maps - would
they then need to be re-run?

Julian

**Comment by zonca** [comment]
> Sounds good. You might also point Elena to the outputs for independent verification/sanity checks.

yes, sure,

> The one issue is that Reijo has been running against the old maps - would they then need to be re-run? Julian

No, but we need to make 2 comparisons and make sure there is agreement.
First compare the new single component maps with the old single component maps.
Second compare the new combined maps with the old combined maps actually used by Reijo, this is particularly important because Reijo produced his own combined maps instead of using my combined maps. I will ping @keskitalo about this when I am ready to do the comparison.

**Comment by zonca** [comment]
@smsimon should we keep using top-hat bandpasses?

**Comment by smsimon** [comment]
Yes, we don't have designs yet for the actual bandpasses

**Pull request merged**
