### PR TITLE
Update instrument model for DC-0 rerun

### PR DESCRIPTION
**Pull request by zonca**
- import configuration from CHLAT only run
- imported new instrument model
- update instrument model from s4sim version e20d9ab

### CODE REVIEW

**Comment by zonca** [comment]
@smsimon it looks like bandpass changed only for CHLAT 30 40 and 220

**Comment by smsimon** [comment]
Yes, those were the only ones that changed. Bands and beams look good. What noise should these maps have? The noise at the nominal observation elevation or the noise at the elevation that TOAST normalized to?

**Comment by zonca** [comment]
> What noise should these maps have? The noise at the nominal observation elevation or the noise at the elevation that TOAST normalized to?

Maps are noiseless, so I removed NET from the table. It was used in the past where I was simulating noise. Now it is only cause for confusion.

**Comment by smsimon** [comment]
OK, sounds good. Bands and beams look good so I am approving

**Review by smsimon — APPROVED** [review]

**Pull request merged**
