### PR TITLE
Rerun combined maps for DC-0 input

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
@jdborrill I would like to rerun the combined maps so they agree to what was used as input to DC-0.

can you check at https://github.com/CMB-S4/s4mapbasedsims/blob/redo_combined/202211_LAT_foregrounds_extragalactic_cmb/combine_maps.py#L8-L36 that these are the combinations we want?

@keskitalo can you please point me and give me access to the combined maps you created and used as input to DC-0? I will check that they agree exactly with what I will produce.

**Comment by zonca** [comment]
there was no CMB unlensed without solar dipole provided by Websky when I ran the simulations, that is the reason the component has a dipole.

**Comment by zonca** [comment]
thanks @keskitalo, in `input_map` I only see the processed foregrounds.
What about the CMB and the lensing signal? Have you postprocessed the output CMB maps?

so from the table in the datachallenge 0 document:
image

it looks like you put the dipole inside the foregrounds map.
So I will create the same with my script and compare the results to make sure they are consistent.

**Comment by jdborrill** [comment]
I only put that in the text because that's what I had understood us to have
used. Please confirm ASAP what the actual combination used was!

Julian

**Comment by keskitalo** [comment]
That was another confusion, it seems. The dipole was in the foreground map only because it came with the CMB. In the corrected foreground maps, both the unlensed CMB and the dipole are removed.

**Comment by zonca** [comment]
## Components mapped in DC-0

* CMB: probably the `cmb` component of the map based simulations, i.e. Lensed CMB with no dipole and no SZ (@keskitalo can you confirm?)
* `combined_foregrounds_cmb_fixdip`: Unlensed CMB + Planck HFI 2018 dipole + Galactic + Extragalactic (with SZ)
* Foregrounds only create in March 2023: `combined_foregrounds_cmb_fixdip` - cmb - dipole, i.e. galactic emissions and extragalactic (with SZ)

**Comment by keskitalo** [comment]
Not quite. The CMB component included the dipole. The foregrounds were originally mapped with the CMB and dipole included but they were removed during the co-add phase.

**Comment by zonca** [comment]
@keskitalo, as suggested by @jdborrill, I am going to put the combined maps under `sky/` while I moved the individual components under `raw`, this is the lensing signal:

`/global/cfs/cdirs/cmbs4/dc/dc0/sky/4096/combined_cmb_lensing_signal`

**Comment by zonca** [comment]
@keskitalo just as a check, can you take a spectrum of the lensing map and compare with the design tool one?

**Comment by zonca** [comment]
@keskitalo I also launched the combine maps script to create the other 2 components, I am writing them directly to CFS:

```
/global/cfs/cdirs/cmbs4/dc/dc0/sky/4096/combined_cmb_unlensed_dipole/0000/cmbs4_combined_cmb_unlensed_dipole_uKCMB_LAT-LFL1_nside4096_0000.fits
```

**Comment by keskitalo** [comment]
The new lensing maps have very similar power as the design tool maps but are not identical.  I assume this was the intention.


image

**Comment by keskitalo** [comment]
Interestingly, a log-log plot shows that the `dc0` lensing map has a prominent quadrupole that was entirely missing in the `dstool` map:
image

Despite being so prominent in the power spectrum, it is not apparent when viewing the maps:
image

**Comment by keskitalo** [comment]
@zonca , can you confirm that the difference is expected?

**Comment by keskitalo** [comment]
Or was it, by any chance, left in the map from the relativistic quadrupole?

**Comment by zonca** [comment]
We shouldn't have any quadruple. That is because I am just fitting the dipole away with healpy and that is not removing the quadruple.

**Comment by zonca** [comment]
Yes, that is what I think.

**Comment by keskitalo** [comment]
Seems like an error then. Do you have the correct dipole+quadrupole template to remove?

**Comment by zonca** [comment]
I'll fix it later today and get back to you.

**Comment by zonca** [comment]
ok @keskitalo, I created a new component named `cmb_unlensed`, this was not available when I ran the initial simulations so for that reason I ran the component with dipole and then removed it.

then I used that component to rerun the combine maps script (see source inside this pull request to double check) and created the new combined maps inside:

     /global/cfs/cdirs/cmbs4/dc/dc0/sky/

can you please rerun the spectra and make sure this is right?

**Comment by keskitalo** [comment]
The quadrupole issue is resolved. The new lensing power spectra now agree very well with the `dstool` ones:
image

**Comment by keskitalo** [comment]
I am comparing the new maps to the old foreground map. The thinking was that if the new unlensed map matched the CMB signal in the old foreground map, we could clean the existing foreground simulations using a new unlensed run.  Unfortunately there is a difference and it is the quadrupole again: 
image

**Comment by zonca** [comment]
Yes, those maps are affected by the same issue.
You need to rerun the foreground map as well.

**Comment by jdborrill** [comment]
In some ways I'd be happier re-running everything from
known/documented/verified inputs rather than performing post-processing
algebra.

J

**Comment by zonca** [comment]
I updated the documentation mentioning the new way the cmb maps are generated.
What is described in the docs is consistent with what is available on CFS at NERSC.

**Pull request merged**
